#!/usr/bin/env bash
# Read-only checks of a deployed instance, run by .github/workflows/diagnostics.yml
# on the self-hosted runner. Prints no secrets: of shared/.env only the names of
# the variables and the values of the non-secret ones are shown.
# Usage: diagnostics.sh <app dir> [log lines] [proxy container] [public url]
set -uo pipefail

APP_DIR=${1:?usage: diagnostics.sh <app dir> [log lines] [proxy container] [public url]}
LINES=${2:-50}
PROXY_CONTAINER=${3:-}
PUBLIC_URL=${4:-}
ENV_FILE="$APP_DIR/shared/.env"

# Values safe to print; everything else (SECRET_KEY, ...) is shown by name only
PUBLIC_VARS=" DEPLOY_METHOD INSTANCE_NAME APP_PORT NETWORK_MODE PROXY_NETWORK BIND_ADDRESS BEHIND_PROXY \
ALLOWED_HOSTS CSRF_TRUSTED_ORIGINS DEBUG TIME_ZONE ID_SERVER RELAY_SERVER RUSTDESK_KEY API_URL \
RUSTDESK_VERSION HEALTHCHECK_URL LOG_LEVEL SERVICE_NAME "

section() { printf '\n::group::%s\n' "$1"; }
end() { echo '::endgroup::'; }
env_value() { sed -n "s/^$1=//p" "$ENV_FILE" | tail -n 1 | tr -d '"'"'"' \r'; }

section "Release"
echo "app dir:         $APP_DIR"
echo "current release: $(cat "$APP_DIR/current_release" 2>/dev/null || echo '-')"
echo "releases:        $(find "$APP_DIR/releases" -mindepth 1 -maxdepth 1 -type d 2>/dev/null | wc -l)"
echo "latest backups:"
# shellcheck disable=SC2012  # names are generated by the deploy script
ls -1t "$APP_DIR/backups" 2>/dev/null | head -n 3 | sed 's/^/  /'
end

section "shared/.env"
if [ -r "$ENV_FILE" ]; then
    grep -E '^[A-Za-z_][A-Za-z0-9_]*=' "$ENV_FILE" | cut -d= -f1 | sort -u | while read -r name; do
        if [[ "$PUBLIC_VARS" == *" $name "* ]]; then
            echo "$name=$(env_value "$name")"
        else
            echo "$name=<hidden>"
        fi
    done
else
    echo "$ENV_FILE is not readable"
fi
end

INSTANCE=$(env_value INSTANCE_NAME 2>/dev/null)
INSTANCE=${INSTANCE:-rustdesk-api}
PORT=$(env_value APP_PORT 2>/dev/null)
PORT=${PORT:-21114}
METHOD=$(env_value DEPLOY_METHOD 2>/dev/null)

if [ "${METHOD:-docker}" = docker ]; then
    section "Container $INSTANCE"
    docker ps -a --filter "name=^${INSTANCE}\$" --format 'status: {{.Status}}\nimage:  {{.Image}}\nports:  {{.Ports}}'
    docker inspect "$INSTANCE" --format 'restarts: {{.RestartCount}}
network mode: {{.HostConfig.NetworkMode}}
networks: {{range $name, $net := .NetworkSettings.Networks}}{{$name}} ({{$net.IPAddress}}) {{end}}
command: {{join .Config.Cmd " "}}' 2>&1
    end

    section "Container log (last $LINES lines)"
    docker logs --tail "$LINES" "$INSTANCE" 2>&1
    end

    section "Response codes in the last 1000 log lines"
    docker logs --tail 1000 "$INSTANCE" 2>&1 \
        | grep -oE '"[A-Z]+ /[^ ?"]*[^"]*" [0-9]{3}' \
        | sed -E 's/"([A-Z]+) ([^ ?]*)[^"]*" ([0-9]{3})/\3 \1 \2/' \
        | sort | uniq -c | sort -rn | head -n 20
    end
else
    SERVICE=$(env_value SERVICE_NAME)
    SERVICE=${SERVICE:-rustdesk-api}
    section "Service $SERVICE"
    systemctl status "$SERVICE" --no-pager 2>&1 | head -n 15
    journalctl -u "$SERVICE" -n "$LINES" --no-pager 2>&1
    end
fi

section "HTTP checks"
check() {
    # prints the status code, or the curl error
    local code
    code=$(curl -s -o /dev/null -w '%{http_code}' --max-time 10 "$@" 2>&1) || true
    echo "$code"
}
echo "host 127.0.0.1:$PORT -> $(check "http://127.0.0.1:$PORT/api/user_action")"
if [ -n "$PROXY_CONTAINER" ]; then
    if docker inspect "$PROXY_CONTAINER" >/dev/null 2>&1; then
        code=$(docker exec "$PROXY_CONTAINER" curl -s -o /dev/null -w '%{http_code}' --max-time 10 \
            "http://$INSTANCE:$PORT/api/user_action" 2>&1) || true
        echo "$PROXY_CONTAINER -> http://$INSTANCE:$PORT: $code"
    else
        echo "container $PROXY_CONTAINER not found"
    fi
fi
if [ -n "$PUBLIC_URL" ]; then
    echo "$PUBLIC_URL -> $(check "${PUBLIC_URL%/}/api/user_action")"
    host=${PUBLIC_URL#*://}
    host=${host%%/*}
    host=${host%%:*}
    echo "http://$host:$PORT (should fail from outside) -> $(check "http://$host:$PORT/api/user_action")"
fi
end

if [ -n "$PROXY_CONTAINER" ] && docker inspect "$PROXY_CONTAINER" >/dev/null 2>&1; then
    # Container log of Nginx Proxy Manager: its own errors (✖ error) and nginx
    # messages; its debug lines like `nginx -t -g "error_log off;"` are skipped
    section "Proxy $PROXY_CONTAINER: errors in the last 200 container log lines"
    docker logs --tail 200 "$PROXY_CONTAINER" 2>&1 \
        | grep -E '✖|\[(error|crit|alert|emerg)\]' | grep -v 'error_log off' | tail -n 20 \
        | grep . || echo "none"
    end

    # nginx error logs of the proxy hosts (Nginx Proxy Manager keeps them in
    # /data/logs): only upstream errors for this instance's port
    section "Proxy $PROXY_CONTAINER: nginx errors for port $PORT"
    docker exec "$PROXY_CONTAINER" sh -c 'tail -q -n 500 /data/logs/proxy-host-*_error.log 2>/dev/null' 2>&1 \
        | grep -F ":$PORT" | tail -n 20 | grep . || echo "none"
    end
fi
